# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

name: SEAPATH SLES 16.0 CI Build

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_type:
          - standalone
          - cluster
          - observer
        cockpit:
          - no-cockpit
          - cockpit
        exclude:
          - image_type: observer
            cockpit: cockpit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl

      - name: Install CQFD
        run: |
          sudo apt-get update
          curl -fsSLo /tmp/cqfd.deb https://github.com/savoirfairelinux/cqfd/releases/download/v5.9.0/cqfd_5.9.0_all.deb
          sudo apt-get install -y /tmp/cqfd.deb

      - name: Build SLES ${{ matrix.image_type }} / ${{ matrix.cockpit }} image
        uses: ./.github/actions/build-sles-image
        with:
          image_type: ${{ matrix.image_type }}
          use_cockpit: ${{ matrix.cockpit == 'cockpit' }}
          ssh_public_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILhk48cr2jsABDIO/CzmiVDidEof3KoXi/L9qniZKBBT seapath-dummy-key'
        env:
          SLES_USERNAME: ${{ secrets.SLES_USERNAME }}
          SLES_PASSWORD: ${{ secrets.SLES_PASSWORD }}
          SLES_TOKEN: ${{ secrets.SLES_TOKEN }}

      - name: Upload build logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: kiwi-logs-${{ matrix.image_type }}-${{ matrix.cockpit }}-${{ github.run_id }}
          path: build/image-root.log
          if-no-files-found: ignore
